# Generated by Django 5.0 on 2023-12-30 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoveEntry",
            new_name="LoveTest",
        ),
    ]
