# Generated by Django 5.0 on 2023-12-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_loveentry_lovetest"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationshipTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("partner_name", models.CharField(max_length=100)),
                ("meet_location", models.CharField(max_length=100)),
                ("feelings", models.CharField(max_length=100)),
                ("better_person", models.CharField(max_length=100)),
                ("result", models.CharField(blank=True, max_length=100, null=True)),
                ("score", models.IntegerField(default=0)),
            ],
        ),
    ]
